"""Initial migration

Revision ID: a6491326dfb0
Revises: 
Create Date: 2026-06-16 18:17:25.079948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6491326dfb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iss_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iss_telemetry_id'), 'iss_telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_iss_telemetry_timestamp'), 'iss_telemetry', ['timestamp'], unique=False)
    op.create_table('launches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('launch_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('rocket_name', sa.String(length=100), nullable=True),
    sa.Column('launch_pad', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('explanation', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_launches_id'), 'launches', ['id'], unique=False)
    op.create_index(op.f('ix_launches_launch_id'), 'launches', ['launch_id'], unique=True)
    op.create_index(op.f('ix_launches_window_start'), 'launches', ['window_start'], unique=False)
    op.create_table('neo_hazards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neo_reference_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nasa_jpl_url', sa.String(length=255), nullable=True),
    sa.Column('absolute_magnitude_h', sa.Float(), nullable=True),
    sa.Column('estimated_diameter_km_max', sa.Float(), nullable=True),
    sa.Column('is_potentially_hazardous_asteroid', sa.Boolean(), nullable=True),
    sa.Column('close_approach_date', sa.Date(), nullable=False),
    sa.Column('miss_distance_km', sa.Float(), nullable=True),
    sa.Column('relative_velocity_kph', sa.Float(), nullable=True),
    sa.Column('explanation', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neo_hazards_close_approach_date'), 'neo_hazards', ['close_approach_date'], unique=False)
    op.create_index(op.f('ix_neo_hazards_id'), 'neo_hazards', ['id'], unique=False)
    op.create_index(op.f('ix_neo_hazards_is_potentially_hazardous_asteroid'), 'neo_hazards', ['is_potentially_hazardous_asteroid'], unique=False)
    op.create_index(op.f('ix_neo_hazards_neo_reference_id'), 'neo_hazards', ['neo_reference_id'], unique=True)
    op.create_table('raw_api_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_api_responses_id'), 'raw_api_responses', ['id'], unique=False)
    op.create_index(op.f('ix_raw_api_responses_source'), 'raw_api_responses', ['source'], unique=False)
    op.create_index(op.f('ix_raw_api_responses_timestamp'), 'raw_api_responses', ['timestamp'], unique=False)
    op.create_table('space_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('peak_time', sa.DateTime(), nullable=True),
    sa.Column('k_index', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('explanation', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_space_weather_event_id'), 'space_weather', ['event_id'], unique=True)
    op.create_index(op.f('ix_space_weather_id'), 'space_weather', ['id'], unique=False)
    op.create_index(op.f('ix_space_weather_start_time'), 'space_weather', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_space_weather_start_time'), table_name='space_weather')
    op.drop_index(op.f('ix_space_weather_id'), table_name='space_weather')
    op.drop_index(op.f('ix_space_weather_event_id'), table_name='space_weather')
    op.drop_table('space_weather')
    op.drop_index(op.f('ix_raw_api_responses_timestamp'), table_name='raw_api_responses')
    op.drop_index(op.f('ix_raw_api_responses_source'), table_name='raw_api_responses')
    op.drop_index(op.f('ix_raw_api_responses_id'), table_name='raw_api_responses')
    op.drop_table('raw_api_responses')
    op.drop_index(op.f('ix_neo_hazards_neo_reference_id'), table_name='neo_hazards')
    op.drop_index(op.f('ix_neo_hazards_is_potentially_hazardous_asteroid'), table_name='neo_hazards')
    op.drop_index(op.f('ix_neo_hazards_id'), table_name='neo_hazards')
    op.drop_index(op.f('ix_neo_hazards_close_approach_date'), table_name='neo_hazards')
    op.drop_table('neo_hazards')
    op.drop_index(op.f('ix_launches_window_start'), table_name='launches')
    op.drop_index(op.f('ix_launches_launch_id'), table_name='launches')
    op.drop_index(op.f('ix_launches_id'), table_name='launches')
    op.drop_table('launches')
    op.drop_index(op.f('ix_iss_telemetry_timestamp'), table_name='iss_telemetry')
    op.drop_index(op.f('ix_iss_telemetry_id'), table_name='iss_telemetry')
    op.drop_table('iss_telemetry')
    # ### end Alembic commands ###
